# Generated by Django 4.1.3 on 2023-01-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_trip', models.CharField(max_length=200)),
                ('Destination', models.CharField(max_length=200)),
                ('Date_of_trip', models.DateTimeField()),
                ('Require_risk_assessment', models.BooleanField()),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_expenses', models.CharField(max_length=200)),
                ('Amount_of_the_expense', models.IntegerField(default=0)),
                ('Time_of_the_expense', models.DateTimeField()),
                ('Name_of_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.detail')),
            ],
        ),
    ]
